# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tarea',
        ),
    ]
