# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_tareas', '0002_auto_20161112_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
